baseurl: "/"
title: "Write Everyday"
page_load_js: "assets/js/main.js"
params:
  header:
    title: Write Everyday
    tagline: Minimal and clean blog theme
    has_nav: true
    has_social: true
  palette: yellow
sass:
  input_file: sass/main.scss.njk
  output_file: assets/css/main.css
  indentWidth: 4
  outputStyle: nested
  precision: 10
